"""
DOCUMENTACIÓN DEL SCRIPT_DOC:
    AUTOR: BJNM
    FECHA DE MODIFICACIÓN/CREACIÓN:
        * V1.0 --> 25/12/2021 (BJNM)
        * V1.1 --> 25/12/2021 (ABCD) 
    FUNCIONES INTERNAS: SUMA
    EXPLICACIÓN: ESTA ES UIN SCRIPT SENCILLO EXPLICATIVO
"""

def SUMA(A,B):
    """
    DOCUMENTACIÓN DE LA FUNCIÓN SUMA:
        AUTOR: BJNM
        FECHA DE MODIFICACIÓN/CREACIÓN:
            * V1.0 --> 25/12/2021 (BJNM)
            * V1.1 --> 25/12/2021 (ABCD) 
        PARÁMETROS: A,B (ENTEROS O CADENAS)
        RETORNO: SUMA O CONCATENACIÓN DE CADENAS
        EXPLICACIÓN: ESTA ES UNA FUNCIÓN SENCILLA EXPLICATIVA
    """
    return A+B
